---
- name: Fail if variable `avail_light_version` is not defined
  ansible.builtin.fail:
    msg: "The variable 'avail_light_version' is not defined. Needs env var AVAIL_LIGHT_VERSION"
  when: avail_light_version == ""

- name: Debug avail_light_version
  debug:
    msg: "avail_light_version: {{ avail_light_version }}"

- name: Setup lightnode
  vars:
    client_version:  "{{ avail_light_version }}"
  block: 
    - ansible.builtin.include_tasks: init.yml
    - ansible.builtin.include_tasks: configure.yml
    - ansible.builtin.include_tasks: datadog.yml
  when: inventory_hostname in groups['lightnode']

- name: Setup fatclients
  vars:
    client_version:  "{{ avail_light_version }}"
  block: 
    - ansible.builtin.include_tasks: init.yml
    - ansible.builtin.include_tasks: configure.yml
    - ansible.builtin.include_tasks: datadog.yml
  when: inventory_hostname in groups['fatclient']