---
# tasks file for roles/slack_handler

- name: Notify Slack of Playbook Failure
  slack:
    username: 'Ansible'
    color: danger
    token: "{{ slack_webhook }}"
    channel: "#eng-node-configuration"
    msg: "Ansible failed on *{{ ansible_hostname }} ({{ inventory_hostname }})* \n
    *Task*: {{ ansible_failed_task.name }} \n
    *Action*: {{ ansible_failed_task.action }} \n
    *Error Message*: \n ```{{ ansible_failed_result | to_nice_json }}``` "
  delegate_to: localhost
  when: ansible_failed_result is defined
  failed_when: True

- name: Notify Slack of Handler Error
  slack:
    username: 'Ansible'
    color: danger
    token: "{{ slack_webhook }}"
    channel: "#avail-deployments"
    msg: "Ansible failed on *{{ ansible_hostname }} ({{ inventory_hostname }})* \n
    *Task*: Handler Error \n
    *Action*: Handler Error \n
    *Error Message*: \n ```Handler Error``` "
  delegate_to: localhost
  when: ansible_failed_result is undefined
  failed_when: True