---
- name: Restart otel
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: otel
    enabled: true

- name: Restart journald
  ansible.builtin.systemd:
    state: restarted
    name: systemd-journald
    enabled: true