- hosts: bootnode
  become: true
  gather_facts: true
  vars:
    bootnode_version: "{{ lookup('env', 'BOOTNODE_VERSION') }}"
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
  tasks:
    - block:
      - include_role:
          name: bootnode
      rescue:
      - include_role:
          name: slack_alert
          tasks_from: failure

- hosts: lightnode
  become: true
  gather_facts: true
  vars:
    avail_light_version: "{{ lookup('env', 'AVAIL_LIGHT_VERSION') }}"
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
    desired_count: "{{ desired_count_lightnode }}"
    service_start: "{{ groups[group_names[0]].index(inventory_hostname) * desired_count }}"
    service_end: "{{ (groups[group_names[0]].index(inventory_hostname) + 1) * desired_count }}"
    total_fc_count: "{{ groups['fatclient'] | length * desired_count_fatclient }}"
  tasks:
    - block:
      - include_role:
          name: lightclient
      rescue:
      - include_role:
          name: slack_alert
          tasks_from: failure
  tags:
    - lightclient

- hosts: fatclient
  become: true
  gather_facts: true
  vars:
    avail_light_version: "{{ lookup('env', 'FATCLIENT_VERSION') }}"
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
    desired_count: "{{ desired_count_fatclient }}"
    service_start: "{{ groups[group_names[0]].index(inventory_hostname) * desired_count }}"
    service_end: "{{ (groups[group_names[0]].index(inventory_hostname) + 1) * desired_count }}"
    total_fc_count: "{{ groups['fatclient'] | length * desired_count_fatclient }}"
  tasks:
    - block:
      - include_role:
          name: lightclient
      rescue:
      - include_role:
          name: slack_alert
          tasks_from: failure
  tags:
    - lightclient

- hosts: otel
  become: true
  gather_facts: true
  vars:
    otel_version: 0.97.0
    avail_light_version: "{{ lookup('env', 'AVAIL_LIGHT_VERSION') | regex_replace('^.*-(v.*)$', '\\1') }}"
    datadog_api_key: "{{ lookup('env', 'DATADOG_API_KEY') }}"
  tasks:
    - block:
      - include_role:
          name: collector
      rescue:
      - include_role:
          name: slack_alert
          tasks_from: failure