name: Common

on:
  workflow_call:
    inputs:
      network:
        required: true
        type: string
      bootnode_version:
        required: false
        type: string
      avail_light_version:
        required: false
        type: string
      fatclient_version:
        required: false
        type: string

    secrets:
      datadog_api_key:
        required: false
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      slack_webhook:
        required: true

env:
  NETWORK: ${{ inputs.network }}
  AVAIL_LIGHT_VERSION: ${{ inputs.avail_light_version }}
  FATCLIENT_VERSION: ${{ inputs.fatclient_version }}
  BOOTNODE_VERSION: ${{ inputs.bootnode_version }}
  DATADOG_API_KEY: ${{ secrets.datadog_api_key }}
  FORCE_COLOR: "1"
  GITHUB_WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  SLACK_WEBHOOK: ${{ secrets.slack_webhook }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/deployments/${{ env.NETWORK }}
   
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: configure aws creds
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: eu-west-1
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}

    - name: terraform init
      run: terraform init
      
    - name: terraform apply
      run: terraform apply --auto-approve

    - name: upload ssh key
      uses: actions/upload-artifact@v4
      with:
        name: ansible-files
        path: |
          ansible/${{ env.NETWORK }}_key
          ansible/inventory/${{ env.NETWORK }}.ini

  ansible:
    runs-on: ubuntu-latest
    needs: terraform
    env:
      ANSIBLE_FORCE_COLOR: "true"
    defaults:
      run:
        working-directory: ansible

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: download ssh key
      uses: actions/download-artifact@v4
      with:
        name: ansible-files
        path: ansible

    - name: show ansible files exists
      run: |
        chmod 0600 ${{ env.NETWORK }}_key
        ls -lash
        cat inventory/${{ env.NETWORK }}.ini

    - name: view ansible inventory
      run: ansible-inventory --inventory inventory/${{ env.NETWORK }}.ini --list

    - name: ping all
      run: ansible all -m ping --inventory inventory/${{ env.NETWORK }}.ini
  
    - name: run bootnode playbook
      if: ${{ env.BOOTNODE_VERSION }}
      run: ansible-playbook playbook.yml -i inventory/${{ env.NETWORK }}.ini --limit bootnode

    - name: run lightnode playbook
      if: ${{ env.AVAIL_LIGHT_VERSION }}
      run: ansible-playbook playbook.yml -i inventory/${{ env.NETWORK }}.ini --limit lightnode

    - name: run fatclient playbook
      if: ${{ env.FATCLIENT_VERSION }}
      run: ansible-playbook playbook.yml -i inventory/${{ env.NETWORK }}.ini --limit fatclient

    # - name: run otel playbook
    #   run: ansible-playbook playbook.yml -i inventory/${{ env.NETWORK }}.ini --limit otel
    
  #   - name: Setup upterm session
  #     uses: lhotari/action-upterm@v1
  #     if: ${{ failure() }}
  #     with:
  #       wait-timeout-minutes: 2

  notify-on-failure:
    needs: [ansible, terraform]
    runs-on: ubuntu-latest
    if: failure()
    steps:
    - name: Notify failure
      run: |
        echo "Job failed, sending notification."
        curl -s -X POST -H 'Content-type: application/json' --data '{"text":"LC Deployment Failed: ${{ env.GITHUB_WORKFLOW_URL }} "}' https://hooks.slack.com/services/${{ secrets.slack_webhook }}
  