name: Deploy Lightclients

on:
  repository_dispatch:
    types: ["binary_release"]

  workflow_dispatch:
    inputs:
      bootnode_version:
        description: 'Bootnode version'
        required: false
      avail_light_version:
        description: 'LC version'
        required: false
      fatclient_version:
        description: 'FC version'
        required: false
      network:
        description: 'Network'
        required: false
      
jobs:
  hex:
    if: ${{ (inputs.network == 'hex') || (github.event_name == 'repository_dispatch') }}
    uses: ./.github/workflows/common.yml
    with:
      network: ${{ inputs.network || 'hex' }}
      avail_light_version: ${{ github.event.client_payload.avail_light_version || inputs.avail_light_version }}
      fatclient_version: ${{ github.event.client_payload.fatclient_version || inputs.fatclient_version }}
      bootnode_version: ${{ github.event.client_payload.bootnode_version || inputs.bootnode_version }}
    secrets:
      datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  turing:
    if: ${{ inputs.network == 'turing' }}
    uses: ./.github/workflows/common.yml
    with:
      network: ${{ inputs.network || 'turing' }}
      avail_light_version: ${{ github.event.client_payload.avail_light_version || inputs.avail_light_version }}
      fatclient_version: ${{ github.event.client_payload.fatclient_version || inputs.fatclient_version }}
      bootnode_version: ${{ github.event.client_payload.bootnode_version || inputs.bootnode_version }}
    secrets:
      datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}

  mainnet:
    if: ${{ inputs.network == 'mainnet' }}
    uses: ./.github/workflows/common.yml
    with:
      network: ${{ inputs.network || 'mainnet' }}
      avail_light_version: ${{ github.event.client_payload.avail_light_version || inputs.avail_light_version }}
      fatclient_version: ${{ github.event.client_payload.fatclient_version || inputs.fatclient_version }}
      bootnode_version: ${{ github.event.client_payload.bootnode_version || inputs.bootnode_version }}
    secrets:
      datadog_api_key: ${{ secrets.DATADOG_API_KEY }}
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
